export const DISTRIBUTE_CACHE_SUCCESS_VALUE = 1

export const DISTRIBUTE_CACHE_SET_SUCCESS_VALUE = 'OK'

export const DISTRIBUTE_CACHE_CLEAR_SUCCESS_VALUE = 'OK'

export const DISTRIBUTE_CACHE_DEFAULT_TTL = 5 * 60 * 1000 // ms.

export const MEMORY_CACHE_DEFAULT_TTL = 5 * 60 * 1000 // ms.
